CFLAGS += -I./sources/bootloader
CPPFLAGS += -I./sources/bootloader

VPATH += ./sources/bootloader

SOURCES += sources/bootloader/main.c
SOURCES += sources/bootloader/boot.c
SOURCES += sources/bootloader/jump.c
SOURCES += sources/bootloader/uart_protocol.c
SOURCES += sources/bootloader/crc.c
SOURCES += sources/bootloader/update.c
SOURCES += sources/bootloader/flash.c
